ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'CHEQUE';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'CLUB';
ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "pay_at_club_only" BOOLEAN NOT NULL DEFAULT false;
